export const GET_CARRITOID = "GET_CARRITOID";
export const GET_CARRITO_USUARIO = "GET_CARRITO_USUARIO";

export const ADD_CARRITO = "ADD_CARRITO";
export const ADD_CARRITO_SUCCESS = "ADD_CARRITO_SUCCESS";
export const ADD_CARRITO_FAIL = "ADD_CARRITO_FAIL";

export const GET_CARRITO_PRODUCTS_REQUEST = "GET_CARRITO_PRODUCTS_REQUEST";
export const GET_CARRITO_PRODUCTS_SUCCESS = "GET_CARRITO_PRODUCTS_SUCCESS";
export const GET_CARRITO_PRODUCTS_FAIL = "GET_CARRITO_PRODUCTS_FAIL";

export const DELETE_CARRITO_PRODUCTS_REQUEST = "DELETE_CARRITO_PRODUCTS_REQUEST";
export const DELETE_CARRITO_PRODUCTS_SUCCESS = "DELETE_CARRITO_PRODUCTS_SUCCESS";
export const DELETE_CARRITO_PRODUCTS_FAIL = "DELETE_CARRITO_PRODUCTS_FAIL";

export const GET_CARRITO_PRODUCT_REQUEST = "GET_CARRITO_PRODUCT_REQUEST";
export const GET_CARRITO_PRODUCT_SUCCESS = "GET_CARRITO_PRODUCT_SUCCESS";
export const GET_CARRITO_PRODUCT_FAIL = "GET_CARRITO_PRODUCT_FAIL";

export const UPDATE_CARRITO_PRODUCT_REQUEST = "UPDATE_CARRITO_PRODUCT_REQUEST";
export const UPDATE_CARRITO_PRODUCT_SUCCESS = "UPDATE_CARRITO_PRODUCT_SUCCESS";
export const UPDATE_CARRITO_PRODUCT_FAIL = "UPDATE_CARRITO_PRODUCT_FAIL";